require('dotenv').config();
const { PDFParse } = require('pdf-parse');
const pixelmatch = require('pixelmatch').default;
const { PNG } = require('pngjs');
const fs = require('fs');
const path = require('path');
const Anthropic = require('@anthropic-ai/sdk');
const Diff = require('diff');

const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
});

/**
 * Extracts text and screenshots from a PDF file.
 */
async function processPDF(pdfPath) {
    const dataBuffer = fs.readFileSync(pdfPath);
    const parser = new PDFParse({ data: new Uint8Array(dataBuffer) });

    // Extract text
    const textResult = await parser.getText();

    // Render pages to screenshots (scale 2.0 for clarity)
    const screenshotResult = await parser.getScreenshot({ scale: 2.0 });

    await parser.destroy();

    return {
        text: textResult.text,
        pages: screenshotResult.pages // Array of { data: Uint8Array, width, height, ... }
    };
}

/**
 * Compares text and returns a summary of changes.
 */
function compareText(text1, text2) {
    const changes = Diff.diffLines(text1, text2);
    let diffSummary = "";
    let hasChanges = false;

    changes.forEach((part) => {
        if (part.added || part.removed) {
            hasChanges = true;
            const prefix = part.added ? "+ " : "- ";
            diffSummary += part.value.split('\n').map(line => line ? prefix + line : '').join('\n');
        }
    });

    return { hasChanges, diffSummary: diffSummary.trim() };
}

/**
 * Interprets the comparison results using Claude by sending original images side-by-side.
 */
async function interpretWithClaude(totalDiffPixels, pageResults, textDiff) {
    if (!process.env.ANTHROPIC_API_KEY) {
        console.warn('\nNote: ANTHROPIC_API_KEY not found in .env. Skipping AI interpretation.');
        return;
    }

    console.log('\nRequesting AI interpretation from Claude (Direct Visual Comparison)...');

    const textDiffContext = textDiff.hasChanges
        ? `TEXTUAL CHANGES DETECTED:\n${textDiff.diffSummary.slice(0, 2000)}${textDiff.diffSummary.length > 2000 ? '... [truncated]' : ''}`
        : "NO TEXTUAL CHANGES DETECTED (The content is identical).";

    try {
        const messages = [
            {
                role: 'user',
                content: [
                    {
                        type: 'text',
                        text: `You are a document comparison expert. I have two versions of a PDF.
                        
                        We are transitioning from one document engine to another. I need you to test wether the new engine produces the same output as the old engine. Minor changes in the documents are allowed, such as different line breaks, slightly different positioning etc. However, the contents of the documents should remain the same and we cannot have major visual disruptions. For instance, if a table is rendered slightly differently, it is acceptable. If a table is missing or has wrong values, it is not acceptable. A table that used to be on a single page and is now split over two pages is also not acceptable.

                        The documents are generated by an automated system, so minor differences are expected. However, we cannot have major visual disruptions.

                        ANALYSIS DATA:
                        - Textual Diff: ${textDiff.hasChanges ? 'Differences found' : 'No changes'}
                        - Visual Diff: ${totalDiffPixels} pixels total differ between the two versions.

                        TEXTUAL DIFF SNIPPET:
                        ${textDiffContext}
                        
                        I am attaching pairs of images (Version 1 and Version 2) for the pages that have visual differences.
                        
                        TASK:
                        1. Compare the pairs of images visually.
                        2. Identify what changed (e.g., layout, color, text content, highlighting).
                        3. Determine if these changes are significant for a human reader or just minor rendering artifacts.
                        
                        OUTPUT
                        Respond in the following JSON format and only in JSON. Do not add any other text.

                        {
                            "isAcceptable": boolean,
                            "reasoning": "string",
                            "similarityScore": number,
                            "pages": [
                                {
                                    "pageNum": number,
                                    "isAcceptable": boolean,
                                    "reasoning": "string"
                                }
                            ]
                        }`
                    }
                ]
            }
        ];

        // Only send the first 3 pages that have differences to avoid hitting payload limits
        // For each page, we send both the original from PDF 1 and PDF 2
        const pagesToAnalyze = pageResults.filter(r => r.diffPixels > 0).slice(0, 3);

        pagesToAnalyze.forEach((res, index) => {
            messages[0].content.push({
                type: 'text',
                text: `--- PAGE ${res.pageNum} COMPARISON ---`
            });

            // Add Image from PDF 1
            messages[0].content.push({
                type: 'text',
                text: `[Page ${res.pageNum} - Version 1]`
            });
            messages[0].content.push({
                type: 'image',
                source: {
                    type: 'base64',
                    media_type: 'image/png',
                    data: res.img1Base64,
                },
            });

            // Add Image from PDF 2
            messages[0].content.push({
                type: 'text',
                text: `[Page ${res.pageNum} - Version 2]`
            });
            messages[0].content.push({
                type: 'image',
                source: {
                    type: 'base64',
                    media_type: 'image/png',
                    data: res.img2Base64,
                },
            });
        });

        const response = await anthropic.messages.create({
            model: process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-latest',
            max_tokens: 1500,
            messages: messages,
        });

        console.log('\n--- Claude\'s Interpretation (Direct Vision) ---');
        console.log(response.content[0].text);
        console.log('----------------------------------------------\n');
    } catch (err) {
        console.error('Error during Claude interpretation:', err.message);
        if (err.message.includes('too large')) {
            console.error('Tip: Try reducing the number of pages sent or the scale of the images.');
        }
    }
}

/**
 * Execution function.
 */
async function comparePDFs(pdfPath1, pdfPath2, outputDir = 'diff_output') {
    console.log('=======================================');
    console.log('         SOCRATES PDF Vergelijking');
    console.log('=======================================');

    // 1. Process PDFs
    console.log('\n[1/3] Extracting Content and Rendering Pages...');
    const result1 = await processPDF(pdfPath1);
    const result2 = await processPDF(pdfPath2);

    // 2. Comparisons
    console.log('\n[2/3] Performing Comparisons...');

    // Text Diff
    const textDiff = compareText(result1.text, result2.text);
    if (textDiff.hasChanges) {
        console.log('Text result: Differences found.');
    } else {
        console.log('Text result: 100% identical.');
    }

    // Visual Diff
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    let pageNum = 1;
    let totalDiffPixels = 0;
    const pageResults = [];

    const maxPages = Math.min(result1.pages.length, result2.pages.length);
    if (result1.pages.length !== result2.pages.length) {
        console.warn(`Warning: Page count mismatch (${result1.pages.length} vs ${result2.pages.length}).`);
    }

    for (let i = 0; i < maxPages; i++) {
        const page1 = result1.pages[i];
        const page2 = result2.pages[i];

        // page.data is Uint8Array from PDFParse.getScreenshot
        const img1 = PNG.sync.read(Buffer.from(page1.data));
        const img2 = PNG.sync.read(Buffer.from(page2.data));

        if (img1.width !== img2.width || img1.height !== img2.height) {
            console.warn(`Page ${pageNum}: Dimensions mismatch. Skipping visual diff.`);
            pageNum++;
            continue;
        }

        const { width, height } = img1;
        const diff = new PNG({ width, height });
        const numDiffPixels = pixelmatch(img1.data, img2.data, diff.data, width, height, { threshold: 0.1 });

        totalDiffPixels += numDiffPixels;
        let diffPath = null;

        if (numDiffPixels > 0) {
            diffPath = path.join(outputDir, `diff_page_${pageNum}.png`);
            fs.writeFileSync(diffPath, PNG.sync.write(diff));
            console.log(`Page ${pageNum}: ~${Math.round(numDiffPixels / 1000)}k pixels differ.`);
        } else {
            console.log(`Page ${pageNum}: No visual differences.`);
        }

        pageResults.push({
            pageNum,
            diffPixels: numDiffPixels,
            diffPath,
            img1Base64: Buffer.from(page1.data).toString('base64'),
            img2Base64: Buffer.from(page2.data).toString('base64')
        });
        pageNum++;
    }

    console.log(`\nVisual comparison complete. Total diff pixels: ${totalDiffPixels}`);

    // 3. AI Interpretation
    console.log('\n[3/3] Performing AI Interpretation...');
    await interpretWithClaude(totalDiffPixels, pageResults, textDiff);
}

// CLI handling
const args = process.argv.slice(2);
if (args.length < 2) {
    console.log('Usage: node index.js <pdf1> <pdf2> [outputDir]');
    process.exit(1);
}

const [pdf1, pdf2, out] = args;
comparePDFs(pdf1, pdf2, out).catch(err => {
    console.error('Error during comparison:', err);
    process.exit(1);
});
